### ISSUE TITLE
Tabs seem to have a different vertical alignement if they are active or not

### ISSUE THREAD

**Issue by thusc** [smartcoop/design#188]
On the page https://design.smart.coop/development/docs/c-tabs.html, if you try the "Tabs (with sections)" (the only ones working on that page; I guess this is because the JS is not made to work on multiple groups of tabs), you can notice a slight difference in vertical alignment of the tab labels.

**Comment by emilyvandewalle** [comment]
This should be fixed now (feel free to reopen if not)

The tabs on the other examples currently don't work because they are more simplified/static examples and this part is not included in them (the tab content):
```
    .c-tabs__section#section1
        p a tab
    .c-tabs__section#section2
        p another tab
    .c-tabs__section#section3
        p a third tab
    .c-tabs__section#section4
        p a fourth tab
    .c-tabs__section#section5
        p a fifth tab
```

If this is included with the right references to the id's multiple tabs should work on one page normally
